In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/matches.csv")

In [ ]:
(df.columns)

Index(['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city',
       'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'match_type'],
      dtype='object')

In [ ]:
df.head()

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,2024,Canada,United States of America,2024/06/01,1,Grand Prairie Stadium,Dallas,United States of America,field,Aaron Jones,RK Illingworth,Sharfuddoula,L Rusere,RB Richardson,United States of America,NaN,7.0,Group
1,2024,Papua New Guinea,West Indies,2024/06/02,2,Providence Stadium,Providence,West Indies,field,RL Chase,AT Holdstock,Rashid Riaz,HDPK Dharmasena,AJ Pycroft,West Indies,NaN,5.0,Group
2,2024,Oman,Namibia,2024/06/02,3,Kensington Oval,Bridgetown,Namibia,field,D Wiese,J Madanagopal,JS Wilson,Asif Yaqoob,RS Madugalle,NaN,NaN,NaN,Group
3,2024,Sri Lanka,South Africa,2024/06/03,4,Nassau County International Cricket Stadium,New York,Sri Lanka,bat,A Nortje,CM Brown,RA Kettleborough,AG Wharf,JJ Crowe,South Africa,NaN,6.0,Group
4,2024,Afghanistan,Uganda,2024/06/03,5,Providence Stadium,Providence,Uganda,field,Fazalhaq Farooqi,Ahsan Raza,HDPK Dharmasena,Rashid Riaz,AJ Pycroft,Afghanistan,125.0,NaN,Group

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
dtype: bool

In [ ]:
df.isnull()

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
45,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
49,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
50,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
51,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull()

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
45,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
49,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
50,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
51,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
df.isnull().sum()

season              0
team1               0
team2               0
date                0
match_number        0
venue               0
city                0
toss_winner         0
toss_decision       0
player_of_match     1
umpire1             0
umpire2             0
reserve_umpire      0
match_referee       0
winner              2
winner_runs        27
winner_wickets     28
match_type          0
dtype: int64

#Check the NULL rows

In [ ]:
df[df["player_of_match"].isnull()]

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
5,2024,Scotland,England,2024/06/04,6,Kensington Oval,Bridgetown,Scotland,bat,NaN,Asif Yaqoob,Nitin Menon,J Madanagopal,RS Madugalle,No Result,NaN,NaN,Group

In [ ]:
df[df['winner'].isnull()]

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
2,2024,Oman,Namibia,2024/06/02,3,Kensington Oval,Bridgetown,Namibia,field,D Wiese,J Madanagopal,JS Wilson,Asif Yaqoob,RS Madugalle,NaN,NaN,NaN,Group
10,2024,Pakistan,United States of America,2024/06/06,11,Grand Prairie Stadium,Dallas,United States of America,field,MD Patel,A Paleker,MA Gough,RJ Tucker,JJ Crowe,NaN,NaN,NaN,Group

In [ ]:
df[df['winner_runs'].isnull()]

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,2024,Canada,United States of America,2024/06/01,1,Grand Prairie Stadium,Dallas,United States of America,field,Aaron Jones,RK Illingworth,Sharfuddoula,L Rusere,RB Richardson,United States of America,NaN,7.0,Group
1,2024,Papua New Guinea,West Indies,2024/06/02,2,Providence Stadium,Providence,West Indies,field,RL Chase,AT Holdstock,Rashid Riaz,HDPK Dharmasena,AJ Pycroft,West Indies,NaN,5.0,Group
2,2024,Oman,Namibia,2024/06/02,3,Kensington Oval,Bridgetown,Namibia,field,D Wiese,J Madanagopal,JS Wilson,Asif Yaqoob,RS Madugalle,NaN,NaN,NaN,Group
3,2024,Sri Lanka,South Africa,2024/06/03,4,Nassau County International Cricket Stadium,New York,Sri Lanka,bat,A Nortje,CM Brown,RA Kettleborough,AG Wharf,JJ Crowe,South Africa,NaN,6.0,Group
5,2024,Scotland,England,2024/06/04,6,Kensington Oval,Bridgetown,Scotland,bat,NaN,Asif Yaqoob,Nitin Menon,J Madanagopal,RS Madugalle,No Result,NaN,NaN,Group
6,2024,Nepal,Netherlands,2024/06/04,7,Grand Prairie Stadium,Dallas,Netherlands,field,TJG Pringle,L Rusere,RJ Tucker,RK Illingworth,RB Richardson,Netherlands,NaN,6.0,Group
7,2024,Ireland,India,2024/06/05,8,Nassau County International Cricket Stadium,New York,India,field,JJ Bumrah,AG Wharf,CB Gaffaney,CM Brown,DC Boon,India,NaN,8.0,Group
8,2024,Papua New Guinea,Uganda,2024/06/05,9,Providence Stadium,Providence,Uganda,field,Riazat Ali Shah,AT Holdstock,Rashid Riaz,HDPK Dharmasena,J Srinath,Uganda,NaN,3.0,Group
10,2024,Pakistan,United States of America,2024/06/06,11,Grand Prairie Stadium,Dallas,United States of America,field,MD Patel,A Paleker,MA Gough,RJ Tucker,JJ Crowe,NaN,NaN,NaN,Group
11,2024,Namibia,Scotland,2024/06/06,12,Kensington Oval,Bridgetown,Namibia,bat,MA Leask,J Madanagopal,Nitin Menon,JS Wilson,AJ Pycroft,Scotland,NaN,5.0,Group
14,2024,Sri Lanka,Bangladesh,2024/06/07,15,Grand Prairie Stadium,Dallas,Bangladesh,field,Rishad Hossain,MA Gough,PR Reiffel,RJ Tucker,JJ Crowe,Bangladesh,NaN,2.0,Group
15,2024,Netherlands,South Africa,2024/06/08,16,Nassau County International Cricket Stadium,New York,South Africa,field,DA Miller,CB Gaffaney,Sharfuddoula,SJ Nogajski,DC Boon,South Africa,NaN,4.0,Group
19,2024,Oman,Scotland,2024/06/09,20,Sir Vivian Richards Stadium,North Sound,Oman,bat,BJ McMullen,A Paleker,CM Brown,AG Wharf,RB Richardson,Scotland,NaN,7.0,Group
21,2024,Canada,Pakistan,2024/06/11,22,Nassau County International Cricket Stadium,New York,Pakistan,field,Mohammad Amir,AT Holdstock,HDPK Dharmasena,PR Reiffel,RS Madugalle,Pakistan,NaN,7.0,Group
22,2024,Namibia,Australia,2024/06/11,24,Sir Vivian Richards Stadium,North Sound,Australia,field,A Zampa,Nitin Menon,Rashid Riaz,A Paleker,J Srinath,Australia,NaN,9.0,Group
23,2024,United States of America,India,2024/06/12,25,Nassau County International Cricket Stadium,New York,India,field,Arshdeep Singh,PR Reiffel,SJ Nogajski,AT Holdstock,RS Madugalle,India,NaN,7.0,Group
26,2024,Oman,England,2024/06/13,28,Sir Vivian Richards Stadium,North Sound,England,field,AU Rashid,Asif Yaqoob,L Rusere,Rashid Riaz,AJ Pycroft,England,NaN,8.0,Group
27,2024,Papua New Guinea,Afghanistan,2024/06/13,29,Brian Lara Stadium,Tarouba,Afghanistan,field,Fazalhaq Farooqi,AG Wharf,MA Gough,Ahsan Raza,DC Boon,Afghanistan,NaN,7.0,Group
29,2024,Uganda,New Zealand,2024/06/14,32,Brian Lara Stadium,Tarouba,New Zealand,field,TG Southee,PR Reiffel,RK Illingworth,Ahsan Raza,DC Boon,New Zealand,NaN,9.0,Group
31,2024,Scotland,Australia,2024/06/15,35,Daren Sammy National Cricket Stadium,Gros Islet,Australia,field,MP Stoinis,Asif Yaqoob,MA Gough,A Paleker,JJ Crowe,Australia,NaN,5.0,Group
32,2024,Ireland,Pakistan,2024/06/16,36,Central Broward Regional Park Stadium Turf Ground,Lauderhill,Pakistan,field,Shaheen Shah Afridi,CB Gaffaney,RJ Tucker,RA Kettleborough,J Srinath,Pakistan,NaN,3.0,Group
35,2024,Papua New Guinea,New Zealand,2024/06/17,39,Brian Lara Stadium,Tarouba,New Zealand,field,LH Ferguson,L Rusere,PR Reiffel,RK Illingworth,DC Boon,New Zealand,NaN,7.0,Group
38,2024,West Indies,England,2024/06/19,42,Daren Sammy National Cricket Stadium,Gros Islet,England,field,PD Salt,Ahsan Raza,Nitin Menon,CM Brown,JJ Crowe,England,NaN,8.0,Group
42,2024,United States of America,West Indies,2024/06/21,46,Kensington Oval,Bridgetown,West Indies,field,RL Chase,A Paleker,PR Reiffel,AG Wharf,DC Boon,West Indies,NaN,9.0,Group
45,2024,United States of America,England,2024/06/23,49,Kensington Oval,Bridgetown,England,field,AU Rashid,CB Gaffaney,JS Wilson,A Paleker,DC Boon,England,NaN,10.0,Group
46,2024,West Indies,South Africa,2024/06/23,50,Sir Vivian Richards Stadium,North Sound,South Africa,field,T Shamsi,AG Wharf,RJ Tucker,Sharfuddoula,RS Madugalle,South Africa,NaN,3.0,Group
49,2024,Afghanistan,South Africa,2024/06/26,53,Brian Lara Stadium,Tarouba,Afghanistan,bat,M Jansen,Nitin Menon,RK Illingworth,Ahsan Raza,RB Richardson,South Africa,NaN,9.0,Semi Final

In [ ]:
df[df['winner_wickets'].isnull()]

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
2,2024,Oman,Namibia,2024/06/02,3,Kensington Oval,Bridgetown,Namibia,field,D Wiese,J Madanagopal,JS Wilson,Asif Yaqoob,RS Madugalle,NaN,NaN,NaN,Group
4,2024,Afghanistan,Uganda,2024/06/03,5,Providence Stadium,Providence,Uganda,field,Fazalhaq Farooqi,Ahsan Raza,HDPK Dharmasena,Rashid Riaz,AJ Pycroft,Afghanistan,125.0,NaN,Group
5,2024,Scotland,England,2024/06/04,6,Kensington Oval,Bridgetown,Scotland,bat,NaN,Asif Yaqoob,Nitin Menon,J Madanagopal,RS Madugalle,No Result,NaN,NaN,Group
9,2024,Australia,Oman,2024/06/05,10,Kensington Oval,Bridgetown,Oman,field,MP Stoinis,Asif Yaqoob,JS Wilson,Nitin Menon,RS Madugalle,Australia,39.0,NaN,Group
10,2024,Pakistan,United States of America,2024/06/06,11,Grand Prairie Stadium,Dallas,United States of America,field,MD Patel,A Paleker,MA Gough,RJ Tucker,JJ Crowe,NaN,NaN,NaN,Group
12,2024,Canada,Ireland,2024/06/07,13,Nassau County International Cricket Stadium,New York,Ireland,field,NR Kirton,RA Kettleborough,SJ Nogajski,CB Gaffaney,RB Richardson,Canada,12.0,NaN,Group
13,2024,Afghanistan,New Zealand,2024/06/07,14,Providence Stadium,Providence,New Zealand,field,Rahmanullah Gurbaz,Ahsan Raza,HDPK Dharmasena,AT Holdstock,J Srinath,Afghanistan,84.0,NaN,Group
16,2024,Australia,England,2024/06/08,17,Kensington Oval,Bridgetown,England,field,A Zampa,JS Wilson,Nitin Menon,J Madanagopal,AJ Pycroft,Australia,36.0,NaN,Group
17,2024,West Indies,Uganda,2024/06/08,18,Providence Stadium,Providence,West Indies,bat,AJ Hosein,HDPK Dharmasena,Rashid Riaz,Ahsan Raza,J Srinath,West Indies,134.0,NaN,Group
18,2024,India,Pakistan,2024/06/09,19,Nassau County International Cricket Stadium,New York,Pakistan,field,JJ Bumrah,RK Illingworth,RJ Tucker,Sharfuddoula,DC Boon,India,6.0,NaN,Group
20,2024,South Africa,Bangladesh,2024/06/10,21,Nassau County International Cricket Stadium,New York,South Africa,bat,H Klaasen,RK Illingworth,SJ Nogajski,PR Reiffel,RS Madugalle,South Africa,4.0,NaN,Group
24,2024,West Indies,New Zealand,2024/06/12,26,Brian Lara Stadium,Tarouba,New Zealand,field,SE Rutherford,Ahsan Raza,AG Wharf,MA Gough,DC Boon,West Indies,13.0,NaN,Group
25,2024,Bangladesh,Netherlands,2024/06/13,27,Arnos Vale Ground,Kingstown,Netherlands,field,Shakib Al Hasan,CM Brown,J Madanagopal,JS Wilson,RB Richardson,Bangladesh,25.0,NaN,Group
28,2024,South Africa,Nepal,2024/06/14,31,Arnos Vale Ground,Kingstown,Nepal,field,T Shamsi,J Madanagopal,JS Wilson,SJ Nogajski,RB Richardson,South Africa,1.0,NaN,Group
30,2024,England,Namibia,2024/06/15,34,Sir Vivian Richards Stadium,North Sound,Namibia,field,HC Brook,AT Holdstock,L Rusere,Nitin Menon,RS Madugalle,England,41.0,NaN,Group
33,2024,Bangladesh,Nepal,2024/06/16,37,Arnos Vale Ground,Kingstown,Nepal,field,Tanzim Hasan Sakib,Ahsan Raza,SJ Nogajski,HDPK Dharmasena,RB Richardson,Bangladesh,21.0,NaN,Group
34,2024,Sri Lanka,Netherlands,2024/06/16,38,Daren Sammy National Cricket Stadium,Gros Islet,Netherlands,field,KIC Asalanka,AG Wharf,A Paleker,Asif Yaqoob,JJ Crowe,Sri Lanka,83.0,NaN,Group
36,2024,West Indies,Afghanistan,2024/06/17,40,Daren Sammy National Cricket Stadium,Gros Islet,Afghanistan,field,N Pooran,A Paleker,CM Brown,MA Gough,JJ Crowe,West Indies,104.0,NaN,Group
37,2024,South Africa,United States of America,2024/06/19,41,Sir Vivian Richards Stadium,North Sound,United States of America,field,Q de Kock,CB Gaffaney,RA Kettleborough,L Rusere,RS Madugalle,South Africa,18.0,NaN,Group
39,2024,India,Afghanistan,2024/06/20,43,Kensington Oval,Bridgetown,India,bat,SA Yadav,PR Reiffel,RJ Tucker,AG Wharf,DC Boon,India,47.0,NaN,Group
40,2024,Bangladesh,Australia,2024/06/20,44,Sir Vivian Richards Stadium,North Sound,Australia,field,PJ Cummins,MA Gough,RK Illingworth,AT Holdstock,RB Richardson,Australia,28.0,NaN,Group
41,2024,South Africa,England,2024/06/21,45,Daren Sammy National Cricket Stadium,Gros Islet,England,field,Q de Kock,CM Brown,Sharfuddoula,CB Gaffaney,JJ Crowe,South Africa,7.0,NaN,Group
43,2024,India,Bangladesh,2024/06/22,47,Sir Vivian Richards Stadium,North Sound,Bangladesh,field,HH Pandya,AT Holdstock,MA Gough,RA Kettleborough,RS Madugalle,India,50.0,NaN,Group
44,2024,Afghanistan,Australia,2024/06/22,48,Arnos Vale Ground,Kingstown,Australia,field,Gulbadin Naib,Ahsan Raza,HDPK Dharmasena,Nitin Menon,JJ Crowe,Afghanistan,21.0,NaN,Group
47,2024,India,Australia,2024/06/24,51,Daren Sammy National Cricket Stadium,Gros Islet,Australia,field,RG Sharma,RK Illingworth,RA Kettleborough,HDPK Dharmasena,JJ Crowe,India,24.0,NaN,Group
48,2024,Afghanistan,Bangladesh,2024/06/24,52,Arnos Vale Ground,Kingstown,Afghanistan,bat,Naveen-ul-Haq,L Rusere,Nitin Menon,Ahsan Raza,RB Richardson,Afghanistan,8.0,NaN,Group
50,2024,India,England,2024/06/27,54,Providence Stadium,Providence,England,field,AR Patel,CB Gaffaney,RJ Tucker,PR Reiffel,JJ Crowe,India,68.0,NaN,Semi Final
51,2024,India,South Africa,2024/06/29,55,Kensington Oval,Bridgetown,India,bat,V Kohli,CB Gaffaney,RK Illingworth,RJ Tucker,RB Richardson,India,7.0,NaN,Final

#Check the relationship

In [ ]:
df[df["winner_runs"].isnull()][["team1", "team2", "winner", "winner_runs", "winner_wickets"]]

,team1,team2,winner,winner_runs,winner_wickets
0,Canada,United States of America,United States of America,NaN,7.0
1,Papua New Guinea,West Indies,West Indies,NaN,5.0
2,Oman,Namibia,NaN,NaN,NaN
3,Sri Lanka,South Africa,South Africa,NaN,6.0
5,Scotland,England,No Result,NaN,NaN
6,Nepal,Netherlands,Netherlands,NaN,6.0
7,Ireland,India,India,NaN,8.0
8,Papua New Guinea,Uganda,Uganda,NaN,3.0
10,Pakistan,United States of America,NaN,NaN,NaN
11,Namibia,Scotland,Scotland,NaN,5.0
14,Sri Lanka,Bangladesh,Bangladesh,NaN,2.0
15,Netherlands,South Africa,South Africa,NaN,4.0
19,Oman,Scotland,Scotland,NaN,7.0
21,Canada,Pakistan,Pakistan,NaN,7.0
22,Namibia,Australia,Australia,NaN,9.0
23,United States of America,India,India,NaN,7.0
26,Oman,England,England,NaN,8.0
27,Papua New Guinea,Afghanistan,Afghanistan,NaN,7.0
29,Uganda,New Zealand,New Zealand,NaN,9.0
31,Scotland,Australia,Australia,NaN,5.0
32,Ireland,Pakistan,Pakistan,NaN,3.0
35,Papua New Guinea,New Zealand,New Zealand,NaN,7.0
38,West Indies,England,England,NaN,8.0
42,United States of America,West Indies,West Indies,NaN,9.0
45,United States of America,England,England,NaN,10.0
46,West Indies,South Africa,South Africa,NaN,3.0
49,Afghanistan,South Africa,South Africa,NaN,9.0

In [ ]:
df[df["winner_wickets"].isnull()][["team1", "team2", "winner", "winner_runs", "winner_wickets"]]

,team1,team2,winner,winner_runs,winner_wickets
2,Oman,Namibia,NaN,NaN,NaN
4,Afghanistan,Uganda,Afghanistan,125.0,NaN
5,Scotland,England,No Result,NaN,NaN
9,Australia,Oman,Australia,39.0,NaN
10,Pakistan,United States of America,NaN,NaN,NaN
12,Canada,Ireland,Canada,12.0,NaN
13,Afghanistan,New Zealand,Afghanistan,84.0,NaN
16,Australia,England,Australia,36.0,NaN
17,West Indies,Uganda,West Indies,134.0,NaN
18,India,Pakistan,India,6.0,NaN
20,South Africa,Bangladesh,South Africa,4.0,NaN
24,West Indies,New Zealand,West Indies,13.0,NaN
25,Bangladesh,Netherlands,Bangladesh,25.0,NaN
28,South Africa,Nepal,South Africa,1.0,NaN
30,England,Namibia,England,41.0,NaN
33,Bangladesh,Nepal,Bangladesh,21.0,NaN
34,Sri Lanka,Netherlands,Sri Lanka,83.0,NaN
36,West Indies,Afghanistan,West Indies,104.0,NaN
37,South Africa,United States of America,South Africa,18.0,NaN
39,India,Afghanistan,India,47.0,NaN
40,Bangladesh,Australia,Australia,28.0,NaN
41,South Africa,England,South Africa,7.0,NaN
43,India,Bangladesh,India,50.0,NaN
44,Afghanistan,Australia,Afghanistan,21.0,NaN
47,India,Australia,India,24.0,NaN
48,Afghanistan,Bangladesh,Afghanistan,8.0,NaN
50,India,England,India,68.0,NaN
51,India,South Africa,India,7.0,NaN

#Handle the Null Values

In [ ]:
df['winner']=df["winner"].fillna("no winner")
df['winner_runs']=df["winner_runs"].fillna(0)
df['winner_wickets']=df["winner_wickets"].fillna(0)
df["player_of_match"]=df["player_of_match"].fillna("no player")

In [ ]:
df.isnull().sum()

season             0
team1              0
team2              0
date               0
match_number       0
venue              0
city               0
toss_winner        0
toss_decision      0
player_of_match    0
umpire1            0
umpire2            0
reserve_umpire     0
match_referee      0
winner             0
winner_runs        0
winner_wickets     0
match_type         0
dtype: int64

#remove extra space

In [ ]:
df["team1"] = df["team1"].str.strip()
df["team2"] = df["team2"].str.strip()
df["venue"] = df["venue"].str.strip()
df["city"] = df["city"].str.strip()

#check datatypes

In [ ]:
df.dtypes

season               int64
team1               object
team2               object
date                object
match_number         int64
venue               object
city                object
toss_winner         object
toss_decision       object
player_of_match     object
umpire1             object
umpire2             object
reserve_umpire      object
match_referee       object
winner              object
winner_runs        float64
winner_wickets     float64
match_type          object
dtype: object

#date column

In [ ]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [ ]:
print(df["date"].dtype)

datetime64[ns]

In [ ]:
df["date"]=pd.to_datetime(df["date"])

#Convert floats to integers runs/wickets are whole numbers

In [ ]:
df["winner_runs"] = df["winner_runs"].astype(int)
df["winner_wickets"] = df["winner_wickets"].astype(int)

In [ ]:
df.dtypes

season                      int64
team1                      object
team2                      object
date               datetime64[ns]
match_number                int64
venue                      object
city                       object
toss_winner                object
toss_decision              object
player_of_match            object
umpire1                    object
umpire2                    object
reserve_umpire             object
match_referee              object
winner                     object
winner_runs               float64
winner_wickets            float64
match_type                 object
dtype: object

In [ ]:
df["date"].dtype

dtype('<M8[ns]')

#Check negative values

In [ ]:
print(df[df["winner_runs"] < 0])
print(df[df["winner_wickets"] < 0])

Empty DataFrame
Columns: [season, team1, team2, date, match_number, venue, city, toss_winner, toss_decision, player_of_match, umpire1, umpire2, reserve_umpire, match_referee, winner, winner_runs, winner_wickets, match_type]
Index: []
Empty DataFrame
Columns: [season, team1, team2, date, match_number, venue, city, toss_winner, toss_decision, player_of_match, umpire1, umpire2, reserve_umpire, match_referee, winner, winner_runs, winner_wickets, match_type]
Index: []

#Check invalid wickets

In [ ]:
print(df[df["winner_wickets"] > 10])

Empty DataFrame
Columns: [season, team1, team2, date, match_number, venue, city, toss_winner, toss_decision, player_of_match, umpire1, umpire2, reserve_umpire, match_referee, winner, winner_runs, winner_wickets, match_type]
Index: []

#final check

In [ ]:
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print(df.dtypes)
print(df.shape)

season             0
team1              0
team2              0
date               0
match_number       0
venue              0
city               0
toss_winner        0
toss_decision      0
player_of_match    0
umpire1            0
umpire2            0
reserve_umpire     0
match_referee      0
winner             0
winner_runs        0
winner_wickets     0
match_type         0
dtype: int64
Duplicates: 0
season               int64
team1               object
team2               object
date                object
match_number         int64
venue               object
city                object
toss_winner         object
toss_decision       object
player_of_match     object
umpire1             object
umpire2             object
reserve_umpire      object
match_referee       object
winner              object
winner_runs        float64
winner_wickets     float64
match_type          object
dtype: object
(52, 18)

#Save cleaned dataset

In [ ]:
df.to_csv("icc_mens_wc_cleaned.csv", index=False)