In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
df=pd.read_excel("/content/Inventory-Records-Sample-Data.xlsx")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 10 columns):
 #   Column                                                                                            Non-Null Count  Dtype
---  ------                                                                                            --------------  -----
 0   Unnamed: 0                                                                                        0 non-null      float64
 1   Product ID                                                                                        46 non-null     object
 2   Product Name                                                                                      46 non-null     object
 3   Opening
Stock                                                                                    46 non-null     int64
 4   Purchase/
Stock in                                                                                46 non-null     int64
 5   Number of
Units Sold                                                                             46 non-null     int64
 6   Hand-In-
Stock                                                                                    46 non-null     int64
 7   Cost Price
Per Unit (USD)                                                                        46 non-null     int64
 8   Cost Price
Total (USD)                                                                            46 non-null     int64
 9   6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0)) ans:smart phone  12 non-null     object
dtypes: float64(1), int64(6), object(3)
memory usage: 3.7+ KB

In [ ]:
df.head()

,Unnamed: 0,Product ID,Product Name,Opening \nStock,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD),"6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0)) ans:smart phone"
0,NaN,P101,Laptop,50,20,10,60,1200,72000,7)avg unit price?=AVERAGE(H7:H47)ans:169.34
1,NaN,P102,Monitor,40,15,5,50,500,25000,8)repeated cost per unit?=MODE(H7:H47) ans:80
2,NaN,P103,Keyboard,60,25,15,70,50,3500,9)mean price?=AVERAGE(I7:I47) ans 8596.14
3,NaN,P104,Headphones,30,10,3,37,100,3700,NaN
4,NaN,P105,Smartphone,70,30,20,80,900,72000,NaN

In [ ]:
df.shape

(46, 10)

In [5]:
df.columns

Index(['Unnamed: 0', 'Product ID', 'Product Name', 'Opening \nStock',
       'Purchase/\nStock in', 'Number of \nUnits Sold', 'Hand-In-\nStock',
       'Cost Price \nPer Unit (USD)', 'Cost Price\nTotal (USD)',
       '6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0)) ans:smart phone'],
      dtype='object')

In [ ]:
df["Product Name"]

0                          Laptop
1                         Monitor
2                        Keyboard
3                      Headphones
4                      Smartphone
5                          Tablet
6                          Router
7             External Hard Drive
8                Wireless Earbuds
9                          Webcam
10                     Desk Chair
11                      Desk Lamp
12                USB Flash Drive
13                 Ethernet Cable
14                    Power Strip
15                 Wireless Mouse
16                Gaming Keyboard
17                   Gaming Mouse
18                 Gaming Headset
19                   Gaming Chair
20                 Gaming Monitor
21                  Graphics Card
22                            CPU
23                    Motherboard
24                            RAM
25                            SSD
26                            HDD
27                   Power Supply
28                        PC Case
29                     CPU Cooler
30                  Monitor Stand
31                      Mouse Pad
32                  Thermal Paste
33           Cable Management Kit
34                   WiFi Adapter
35             External DVD Drive
36                  Printer Cable
37               Keyboard Cleaner
38             Laptop Cooling Pad
39                        USB Hub
40    Anti-Glare Screen Protector
41                  USB-C Adapter
42                  Laptop Sleeve
43               Wireless Charger
44                    USB-C Cable
45                    Gaming Desk
Name: Product Name, dtype: object

In [ ]:
df.isnull()

,Unnamed: 0,Product ID,Product Name,Opening \nStock,Purchase/\nStock in,Number of \nUnits Sold,Hand-In-\nStock,Cost Price \nPer Unit (USD),Cost Price\nTotal (USD),"6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0)) ans:smart phone"
0,True,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,False,True
5,True,False,False,False,False,False,False,False,False,True
6,True,False,False,False,False,False,False,False,False,True
7,True,False,False,False,False,False,False,False,False,True
8,True,False,False,False,False,False,False,False,False,False
9,True,False,False,False,False,False,False,False,False,False
10,True,False,False,False,False,False,False,False,False,False
11,True,False,False,False,False,False,False,False,False,False
12,True,False,False,False,False,False,False,False,False,False
13,True,False,False,False,False,False,False,False,False,False
14,True,False,False,False,False,False,False,False,False,False
15,True,False,False,False,False,False,False,False,False,False
16,True,False,False,False,False,False,False,False,False,False
17,True,False,False,False,False,False,False,False,False,True
18,True,False,False,False,False,False,False,False,False,True
19,True,False,False,False,False,False,False,False,False,True
20,True,False,False,False,False,False,False,False,False,True
21,True,False,False,False,False,False,False,False,False,True
22,True,False,False,False,False,False,False,False,False,True
23,True,False,False,False,False,False,False,False,False,True
24,True,False,False,False,False,False,False,False,False,True
25,True,False,False,False,False,False,False,False,False,True
26,True,False,False,False,False,False,False,False,False,True
27,True,False,False,False,False,False,False,False,False,True
28,True,False,False,False,False,False,False,False,False,True
29,True,False,False,False,False,False,False,False,False,True
30,True,False,False,False,False,False,False,False,False,True
31,True,False,False,False,False,False,False,False,False,True
32,True,False,False,False,False,False,False,False,False,True
33,True,False,False,False,False,False,False,False,False,True
34,True,False,False,False,False,False,False,False,False,True
35,True,False,False,False,False,False,False,False,False,True
36,True,False,False,False,False,False,False,False,False,True
37,True,False,False,False,False,False,False,False,False,True
38,True,False,False,False,False,False,False,False,False,True
39,True,False,False,False,False,False,False,False,False,True
40,True,False,False,False,False,False,False,False,False,True
41,True,False,False,False,False,False,False,False,False,True
42,True,False,False,False,False,False,False,False,False,True
43,True,False,False,False,False,False,False,False,False,True
44,True,False,False,False,False,False,False,False,False,True
45,True,False,False,False,False,False,False,False,False,True

In [ ]:
df.isnull().sum()

Unnamed: 0                                                                                          46
Product ID                                                                                           0
Product Name                                                                                         0
Opening \nStock                                                                                      0
Purchase/\nStock in                                                                                  0
Number of \nUnits Sold                                                                               0
Hand-In-\nStock                                                                                      0
Cost Price \nPer Unit (USD)                                                                          0
Cost Price\nTotal (USD)                                                                              0
6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0)) ans:smart phone    34
dtype: int64

#remove unwaanted column

In [27]:
df.pop("Unnamed: 0")

KeyError: 'Unnamed: 0'

#6)which product had max opening stock?=INDEX(C7:C47,MATCH(MAX(D7:D47),D7:D47,0))

In [14]:
df=df.drop(columns=df.columns[-1])

In [18]:
df.duplicated().sum()

np.int64(0)

#remove unwanted spaces.

In [19]:
df["Product ID"]=df["Product ID"].str.strip()

In [20]:
df["Product Name"]=df["Product Name"].str.strip()

In [22]:
df.dtypes

Product ID                     object
Product Name                   object
Opening \nStock                 int64
Purchase/\nStock in             int64
Number of \nUnits Sold          int64
Hand-In-\nStock                 int64
Cost Price \nPer Unit (USD)     int64
Cost Price\nTotal (USD)         int64
dtype: object

#final check

In [29]:
print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())

(46, 8)
Product ID                     0
Product Name                   0
Opening \nStock                0
Purchase/\nStock in            0
Number of \nUnits Sold         0
Hand-In-\nStock                0
Cost Price \nPer Unit (USD)    0
Cost Price\nTotal (USD)        0
dtype: int64
0

#Save the cleaned dataset

In [31]:
df.to_csv(
    "/content/Cleaned_Inventory_Records.csv",
    index=False
)