In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("/content/NESTLE SALES DATASET.xlsx")

In [ ]:
df.shape

(18116, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18116 entries, 0 to 18115
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18116 non-null  object
 1   Unnamed: 1  18116 non-null  object
 2   Unnamed: 2  18116 non-null  object
 3   Unnamed: 3  18116 non-null  object
 4   Unnamed: 4  18116 non-null  object
 5   Unnamed: 5  18116 non-null  object
 6   Unnamed: 6  18116 non-null  object
 7   Unnamed: 7  18116 non-null  object
dtypes: object(8)
memory usage: 1.1+ MB

In [ ]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Sales ID,Date,Product Name,Total Revenue,Sales Location,Sales Medium,Sales count,Product Count
1,AT-18056,2020-06-07 00:00:00,Nescafe,279.3,Australian Capital Territory,Online,1,1
2,AT-9867,2019-05-14 00:00:00,Nescafe,263.46,Australian Capital Territory,Direct,1,1
3,AT-11225,2019-07-07 00:00:00,Nescafe,258.72,Australian Capital Territory,Online,1,1
4,AT-3208,2018-06-25 00:00:00,Nescafe,236.88,Australian Capital Territory,Online,1,1

#The first row as column names

In [ ]:
df.iloc[0]

Unnamed: 0          Sales ID
Unnamed: 1              Date
Unnamed: 2      Product Name
Unnamed: 3     Total Revenue
Unnamed: 4    Sales Location
Unnamed: 5      Sales Medium
Unnamed: 6       Sales count
Unnamed: 7     Product Count
Name: 0, dtype: object

# Remove First

In [ ]:
df.iloc[1:].reset_index(drop=True)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,AT-18056,2020-06-07 00:00:00,Nescafe,279.3,Australian Capital Territory,Online,1,1
1,AT-9867,2019-05-14 00:00:00,Nescafe,263.46,Australian Capital Territory,Direct,1,1
2,AT-11225,2019-07-07 00:00:00,Nescafe,258.72,Australian Capital Territory,Online,1,1
3,AT-3208,2018-06-25 00:00:00,Nescafe,236.88,Australian Capital Territory,Online,1,1
4,AT-18812,2020-07-04 00:00:00,Nescafe,235.2,Australian Capital Territory,Online,1,1
...,...,...,...,...,...,...,...,...
18110,AT-15454,2020-01-10 00:00:00,Nescafe,257.25,Western Australia,Online,1,1
18111,AT-16636,2020-03-28 00:00:00,Nescafe,220.5,Western Australia,Online,1,1
18112,AT-16118,2020-02-26 00:00:00,Nescafe,171.5,Western Australia,Online,1,1
18113,AT-19208,2020-07-18 00:00:00,Nescafe,130.46,Western Australia,Online,1,1
18114,AT-20288,2020-08-27 00:00:00,Nescafe,130.46,Western Australia,Online,1,1

In [ ]:
df.columns.to_list()

['Unnamed: 0',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7']

#METHOD2

In [ ]:

df.columns = df.iloc[0].astype(str).str.strip()
df = df.iloc[1:].reset_index(drop=True)

print(df.columns.tolist())
print(df.head())

['Sales ID', 'Date', 'Product Name', 'Total Revenue', 'Sales Location', 'Sales Medium', 'Sales count', 'Product Count']
0  Sales ID                 Date Product Name Total Revenue  \
0  AT-18056  2020-06-07 00:00:00      Nescafe         279.3
1   AT-9867  2019-05-14 00:00:00      Nescafe        263.46
2  AT-11225  2019-07-07 00:00:00      Nescafe        258.72
3   AT-3208  2018-06-25 00:00:00      Nescafe        236.88
4  AT-18812  2020-07-04 00:00:00      Nescafe         235.2

0                Sales Location Sales Medium Sales count Product Count
0  Australian Capital Territory       Online           1             1
1  Australian Capital Territory       Direct           1             1
2  Australian Capital Territory       Online           1             1
3  Australian Capital Territory       Online           1             1
4  Australian Capital Territory       Online           1             1

In [ ]:
df.columns

Index(['Sales ID', 'Date', 'Product Name', 'Total Revenue', 'Sales Location',
       'Sales Medium', 'Sales count', 'Product Count'],
      dtype='object', name=0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18115 entries, 0 to 18114
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sales ID        18115 non-null  object
 1   Date            18115 non-null  object
 2   Product Name    18115 non-null  object
 3   Total Revenue   18115 non-null  object
 4   Sales Location  18115 non-null  object
 5   Sales Medium    18115 non-null  object
 6   Sales count     18115 non-null  object
 7   Product Count   18115 non-null  object
dtypes: object(8)
memory usage: 1.1+ MB

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18110    False
18111    False
18112    False
18113    False
18114    False
Length: 18115, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull()

,Sales ID,Date,Product Name,Total Revenue,Sales Location,Sales Medium,Sales count,Product Count
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
18110,False,False,False,False,False,False,False,False
18111,False,False,False,False,False,False,False,False
18112,False,False,False,False,False,False,False,False
18113,False,False,False,False,False,False,False,False
18114,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

0
Sales ID          0
Date              0
Product Name      0
Total Revenue     0
Sales Location    0
Sales Medium      0
Sales count       0
Product Count     0
dtype: int64

In [ ]:
df.dtypes

0
Sales ID          object
Date              object
Product Name      object
Total Revenue     object
Sales Location    object
Sales Medium      object
Sales count       object
Product Count     object
dtype: object

# Convert Date to datetime

In [ ]:

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

#Convert numeric columns to numeric data types

In [ ]:
numeric_columns = ["Total Revenue","Sales count","Product Count"]
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df.dtypes

0
Sales ID                  object
Date              datetime64[ns]
Product Name              object
Total Revenue            float64
Sales Location            object
Sales Medium              object
Sales count                int64
Product Count              int64
dtype: object

In [ ]:
df.to_csv("NESTLE SALES DATASET.csv", index=False)

In [ ]:
from google.colab import files
files.download("NESTLE SALES DATASET.csv")