In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("/content/Technological-Products-Sample-Data.xlsx")

In [ ]:
df.shape

(30, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              30 non-null     object
 1   Device             30 non-null     object
 2   Model              30 non-null     object
 3   Country of Origin  30 non-null     object
 4   Date of Release    30 non-null     datetime64[ns]
 5   Price (USD)        30 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.5+ KB

In [ ]:
(df.columns)

Index(['Brand', 'Device', 'Model', 'Country of Origin', 'Date of Release',
       'Price (USD)'],
      dtype='object')

In [ ]:
df["Brand"]

0         Apple
1       Samsung
2        Google
3          Sony
4     Microsoft
5          Dell
6            HP
7        Lenovo
8          Asus
9          Acer
10        Apple
11      Samsung
12       Google
13         Sony
14    Microsoft
15         Dell
16           HP
17       Lenovo
18         Asus
19         Acer
20        Apple
21      Samsung
22       Google
23         Sony
24    Microsoft
25         Dell
26           HP
27       Lenovo
28         Asus
29         Acer
Name: Brand, dtype: object

In [ ]:
df.isnull()

    Brand  Device  Model  Country of Origin  Date of Release  Price (USD)
0   False   False  False              False            False        False
1   False   False  False              False            False        False
2   False   False  False              False            False        False
3   False   False  False              False            False        False
4   False   False  False              False            False        False
5   False   False  False              False            False        False
6   False   False  False              False            False        False
7   False   False  False              False            False        False
8   False   False  False              False            False        False
9   False   False  False              False            False        False
10  False   False  False              False            False        False
11  False   False  False              False            False        False
12  False   False  False              False            False        False
13  False   False  False              False            False        False
14  False   False  False              False            False        False
15  False   False  False              False            False        False
16  False   False  False              False            False        False
17  False   False  False              False            False        False
18  False   False  False              False            False        False
19  False   False  False              False            False        False
20  False   False  False              False            False        False
21  False   False  False              False            False        False
22  False   False  False              False            False        False
23  False   False  False              False            False        False
24  False   False  False              False            False        False
25  False   False  False              False            False        False
26  False   False  False              False            False        False
27  False   False  False              False            False        False
28  False   False  False              False            False        False
29  False   False  False              False            False        False

In [ ]:
df.drop('Unnamed: 0',axis=1,inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
df.isnull().sum()

Brand                0
Device               0
Model                0
Country of Origin    0
Date of Release      0
Price (USD)          0
dtype: int64

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

Brand                10
Device               28
Model                28
Country of Origin     6
Date of Release      30
Price (USD)          20
dtype: int64

In [ ]:
df.dtypes

Brand                        object
Device                       object
Model                        object
Country of Origin            object
Date of Release      datetime64[ns]
Price (USD)                   int64
dtype: object

In [ ]:
df["Brand"].value_counts()

Brand
Apple        3
Samsung      3
Google       3
Sony         3
Microsoft    3
Dell         3
HP           3
Lenovo       3
Asus         3
Acer         3
Name: count, dtype: int64

In [ ]:
df["Device"].value_counts()

Device
Galaxy         2
Surface        2
Pixel          1
iPhone         1
PlayStation    1
XPS            1
Spectre        1
ThinkPad       1
ROG            1
Predator       1
MacBook        1
Odyssey        1
Pixelbook      1
Xperia         1
Xbox           1
Alienware      1
Pavilion       1
IdeaPad        1
ZenBook        1
Swift          1
iPad           1
Nest           1
WH             1
UltraSharp     1
Elite          1
Legion         1
TUF            1
Aspire         1
Name: count, dtype: int64

In [ ]:
df['Country of Origin'].value_counts()

Country of Origin
United States    14
Taiwan            6
China             4
South Korea       3
Japan             2
Malaysia          1
Name: count, dtype: int64

In [ ]:
df["Model"].value_counts()

Model
5                2
x360             2
S21 Ultra        1
13 Pro Max       1
6 Pro            1
Laptop 4         1
13               1
X1 Carbon        1
Zephyrus G14     1
Helios 300       1
Pro 14-inch      1
G9               1
Go               1
1 III            1
Series X         1
m15 R5           1
5 Pro            1
14               1
3                1
Pro 12.9-inch    1
Tab S7+          1
Hub Max          1
1000XM4          1
Pro 8            1
U2720Q           1
Dragonfly        1
7i               1
Gaming A15       1
Name: count, dtype: int64

In [ ]:
df["Brand"] = df["Brand"].str.strip()
df["Device"] = df["Device"].str.strip()
df["Model"] = df["Model"].str.strip()
df["Country of Origin"] = df["Country of Origin"].str.strip()

In [ ]:
df.head()

,Brand,Device,Model,Country of Origin,Date of Release,Price (USD)
0,Apple,iPhone,13 Pro Max,United States,2021-09-24,1099
1,Samsung,Galaxy,S21 Ultra,South Korea,2021-01-29,1199
2,Google,Pixel,6 Pro,United States,2021-10-19,899
3,Sony,PlayStation,5,Japan,2020-11-12,499
4,Microsoft,Surface,Laptop 4,United States,2021-04-15,999

In [ ]:
df["Brand"].unique()

array(['Apple', 'Samsung', 'Google', 'Sony', 'Microsoft', 'Dell', 'HP',
       'Lenovo', 'Asus', 'Acer'], dtype=object)

In [ ]:
df["Price (USD)"].describe()

count      30.000000
mean     1056.000000
std       469.880029
min       229.000000
25%       711.500000
50%       999.000000
75%      1336.500000
max      1999.000000
Name: Price (USD), dtype: float64

In [ ]:
df[df["Price (USD)"] < 0]

Empty DataFrame
Columns: [Brand, Device, Model, Country of Origin, Date of Release, Price (USD)]
Index: []

In [ ]:
df[df["Price (USD)"] == 0]

Empty DataFrame
Columns: [Brand, Device, Model, Country of Origin, Date of Release, Price (USD)]
Index: []

In [ ]:
df["Price (USD)"].sort_values().head()

22    229
23    349
3     499
14    499
25    499
Name: Price (USD), dtype: int64

In [ ]:
df["Price (USD)"].sort_values(ascending=False).head()

10    1999
15    1999
26    1799
11    1699
8     1499
Name: Price (USD), dtype: int64

In [ ]:
df["Date of Release"].max()

Timestamp('2021-10-26 00:00:00')

In [ ]:
df["Date of Release"].min()

Timestamp('2020-07-22 00:00:00')

In [ ]:
df["Date of Release"].sort_values().head()

11   2020-07-22
23   2020-08-06
21   2020-08-21
14   2020-11-10
3    2020-11-12
Name: Date of Release, dtype: datetime64[ns]

In [ ]:
Q1 = df["Price (USD)"].quantile(0.25)
Q3 = df["Price (USD)"].quantile(0.75)

In [ ]:
iqr=Q3-Q1

In [ ]:
lower_bound=Q1-1.5*iqr
upper_bound=Q3+1.5*iqr

In [ ]:
outliers=df[(df["Price (USD)"]<lower_bound) | (df["Price (USD)"]>upper_bound)]

In [104]:
df.to_csv("Technological-Products-Cleaned.csv", index=False)