In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/Zudio_clean_sales_data.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5861 entries, 0 to 5860
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      5861 non-null   object
 1   Country                    5861 non-null   object
 2   State                      5861 non-null   object
 3   City                       5861 non-null   object
 4   Category                   5861 non-null   object
 5   Clothing Type              5861 non-null   object
 6   Store Number               5861 non-null   int64
 7   Postal Code                5861 non-null   int64
 8   Store Type                 5861 non-null   object
 9   Store Open Date            5861 non-null   object
 10  Selling Area Size (sq ft)  5861 non-null   int64
 11  Store Manager              5861 non-null   object
 12  Manager ID                 5861 non-null   object
 13  Store Address              5861 non-null   object
 14  Contact Information        5861 non-null   object
 15  Operating Hours            5861 non-null   object
 16  Staff Count                5861 non-null   int64
 17  Parking Availability       5861 non-null   object
 18  Security Features          5861 non-null   object
 19  Order ID                   5861 non-null   int64
 20  Order Date                 5861 non-null   object
 21  Month                      5861 non-null   object
 22  Customer ID                5861 non-null   int64
 23  Customer Name              5861 non-null   object
 24  Product ID                 5861 non-null   int64
 25  Price                      5861 non-null   int64
 26  Quantity                   5861 non-null   int64
 27  Sales Profit               5861 non-null   float64
 28  total                      5861 non-null   int64
dtypes: float64(1), int64(10), object(18)
memory usage: 1.3+ MB

In [7]:
df.shape

(5861, 29)

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5856    False
5857    False
5858    False
5859    False
5860    False
Length: 5861, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
(df.columns)

Index(['Store', 'Country', 'State', 'City', 'Category', 'Clothing Type',
       'Store Number', 'Postal Code', 'Store Type', 'Store Open Date',
       'Selling Area Size (sq ft)', 'Store Manager', 'Manager ID',
       'Store Address', 'Contact Information', 'Operating Hours',
       'Staff Count', 'Parking Availability', 'Security Features', 'Order ID',
       'Order Date', 'Month', 'Customer ID', 'Customer Name', 'Product ID',
       'Price', 'Quantity', 'Sales Profit', 'total'],
      dtype='object')

In [ ]:
df["Clothing Type"]

0        Dresses
1         Skirts
2        Hoodies
3        Dresses
4        Dresses
          ...
5856       Jeans
5857     Jackets
5858    T-shirts
5859       Shoes
5860      Shirts
Name: Clothing Type, Length: 5861, dtype: object

In [ ]:
df.isnull()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit,total
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5856,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5857,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5858,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5859,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5860,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Store                        0
Country                      0
State                        0
City                         0
Category                     0
Clothing Type                0
Store Number                 0
Postal Code                  0
Store Type                   0
Store Open Date              0
Selling Area Size (sq ft)    0
Store Manager                0
Manager ID                   0
Store Address                0
Contact Information          0
Operating Hours              0
Staff Count                  0
Parking Availability         0
Security Features            0
Order ID                     0
Order Date                   0
Month                        0
Customer ID                  0
Customer Name                0
Product ID                   0
Price                        0
Quantity                     0
Sales Profit                 0
total                        0
dtype: int64

In [ ]:
df.select_dtypes(include="number").columns

Index(['Store Number', 'Postal Code', 'Selling Area Size (sq ft)',
       'Staff Count', 'Order ID', 'Customer ID', 'Product ID', 'Price',
       'Quantity', 'Sales Profit', 'total'],
      dtype='object')

In [12]:
text_columns = df.select_dtypes(include="object").columns
for col in text_columns:
    df[col] = df[col].str.strip()

In [9]:
df.head()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit,total
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0,9790
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2,2078
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0,2890
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,46682,2024-03-27,March,106146,Derek Orozco,991,2469,6,5925.6,14814
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,58242,2024-04-08,April,264070,Victor Arnold,479,1105,6,2652.0,6630

In [10]:
df.describe()

,Store Number,Postal Code,Selling Area Size (sq ft),Staff Count,Order ID,Customer ID,Product ID,Price,Quantity,Sales Profit,total
count,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000,5861.000000
mean,50.624296,420048.399932,1111.022010,11.442587,54995.714895,551773.018598,601.864016,1758.587613,4.483535,3142.273332,7855.683330
std,29.213200,11665.620261,193.723166,5.151691,25951.758277,261435.203072,231.738428,714.706314,2.281311,2129.766921,5324.417302
min,1.000000,400010.000000,800.000000,3.000000,10008.000000,100153.000000,204.000000,499.000000,1.000000,200.400000,501.000000
25%,25.000000,409923.000000,950.000000,7.000000,33261.000000,321312.000000,401.000000,1137.000000,3.000000,1400.000000,3500.000000
50%,51.000000,420245.000000,1100.000000,11.000000,55017.000000,550298.000000,600.000000,1779.000000,4.000000,2652.000000,6630.000000
75%,76.000000,430209.000000,1300.000000,16.000000,77506.000000,781121.000000,803.000000,2368.000000,6.000000,4516.000000,11290.000000
max,100.000000,439985.000000,1400.000000,20.000000,99981.000000,999858.000000,999.000000,2999.000000,8.000000,9590.400000,23976.000000

In [11]:
df["total"].describe()

count     5861.000000
mean      7855.683330
std       5324.417302
min        501.000000
25%       3500.000000
50%       6630.000000
75%      11290.000000
max      23976.000000
Name: total, dtype: float64

In [16]:
Q1 = df["Price"].quantile(0.25)
Q3 = df["Price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [21]:
outliers = df[(df["Price"] < lower)|(df["Price"] > upper)]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5861 entries, 0 to 5860
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      5861 non-null   object
 1   Country                    5861 non-null   object
 2   State                      5861 non-null   object
 3   City                       5861 non-null   object
 4   Category                   5861 non-null   object
 5   Clothing Type              5861 non-null   object
 6   Store Number               5861 non-null   int64
 7   Postal Code                5861 non-null   int64
 8   Store Type                 5861 non-null   object
 9   Store Open Date            5861 non-null   object
 10  Selling Area Size (sq ft)  5861 non-null   int64
 11  Store Manager              5861 non-null   object
 12  Manager ID                 5861 non-null   object
 13  Store Address              5861 non-null   object
 14  Contact Information        5861 non-null   object
 15  Operating Hours            5861 non-null   object
 16  Staff Count                5861 non-null   int64
 17  Parking Availability       5861 non-null   object
 18  Security Features          5861 non-null   object
 19  Order ID                   5861 non-null   int64
 20  Order Date                 5861 non-null   object
 21  Month                      5861 non-null   object
 22  Customer ID                5861 non-null   int64
 23  Customer Name              5861 non-null   object
 24  Product ID                 5861 non-null   int64
 25  Price                      5861 non-null   int64
 26  Quantity                   5861 non-null   int64
 27  Sales Profit               5861 non-null   float64
 28  total                      5861 non-null   int64
dtypes: float64(1), int64(10), object(18)
memory usage: 1.3+ MB

In [23]:
df.shape

(5861, 29)

In [24]:
df.isnull().sum()

Store                        0
Country                      0
State                        0
City                         0
Category                     0
Clothing Type                0
Store Number                 0
Postal Code                  0
Store Type                   0
Store Open Date              0
Selling Area Size (sq ft)    0
Store Manager                0
Manager ID                   0
Store Address                0
Contact Information          0
Operating Hours              0
Staff Count                  0
Parking Availability         0
Security Features            0
Order ID                     0
Order Date                   0
Month                        0
Customer ID                  0
Customer Name                0
Product ID                   0
Price                        0
Quantity                     0
Sales Profit                 0
total                        0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.head()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit,total
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0,9790
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2,2078
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0,2890
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,46682,2024-03-27,March,106146,Derek Orozco,991,2469,6,5925.6,14814
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,58242,2024-04-08,April,264070,Victor Arnold,479,1105,6,2652.0,6630

In [27]:
df.to_csv("/content/Zudio_clean_sales_data.csv",index=False)